version: '3'


# Volumes
volumes:
  mariadb:
    name: mariadb
    external: true
  wordpress:
    name: wordpress
    external: true
  static:
    name: static
    external: true

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    # volumes:
    #   - mariadb:/var/lib/mysql restart:unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    # volumes:
    # - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on: # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443" # on indique le port qui sera exposé a la machine locale
    restart: on-failure # Ici nous changeons, le container redémarrera uniquement en cas de crash.

  wordpress:
    container_name: wordpress
    env_file: .env
    # volumes:
    # - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on: # WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
    - mariadb
    restart: on-failure
    expose:
    - "9000"

networks:
  inception:
    driver: bridge
