services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DATABASE_ROOT_PASSWORD
        - WORDPRESS_DATABASE
        - WORDPRESS_DATABASE_USER
        - WORDPRESS_DATABASE_USER_PASSWORD
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    restart: always
    expose:
      - "9000"

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    ports:
      - "443:443"
    expose:
      - "443"
    restart: on-failure

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pgouasmi/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pgouasmi/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge
